"""add inventory and stock movements

Revision ID: b2b58355b00c
Revises: a2229e7b697e
Create Date: 2026-09-19 16:23:15.483084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b58355b00c'
down_revision: Union[str, Sequence[str], None] = 'a2229e7b697e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchase_orders_warehouse_id'), 'purchase_orders', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('fk_purchase_orders_warehouse_id'), 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'warehouses', ['warehouse_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_purchase_orders_warehouse_id'), 'purchase_orders', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_index(op.f('ix_purchase_orders_warehouse_id'), table_name='purchase_orders')
    op.alter_column('purchase_orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
